name: cr front
#funciona ok
on:
  push:
    tags: ["v*.*.*"] # Se ejecuta cuando se hace un push a una etiqueta que empiece por v
    #branches:
     # - main # Se ejecuta cuando hay un push a la rama main
  workflow_dispatch: # Se ejecuta cuando se hace un disparo manual

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio karlosudpv04/my-ecomerce-front
      - name: Checkout code from karlosudpv04/my-ecomerce-front
        uses: actions/checkout@v3
        with:
          repository: karlosudpv04/my-ecomerce-front  # Especificar el repositorio donde está el Dockerfile


      # Paso 2: Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: karlostcp
          password: ${{ secrets.MI_PTA_DOCKERHUB }}

      # Paso 3: Crear la imagen de Docker desde el Dockerfile en el repositorio
      - name: Build Docker Image
        run: |
          docker build -t karlostcp/my-ecomerce-front:${{ github.sha }} -f Dockerfile .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push karlostcp/my-ecomerce-front:${{ github.sha }}


